---
defaults: &defaults
  docker:
    - image: canonicalwebteam/dev
  environment:
  working_directory: ~/project

version: 2
jobs:
  linkchecker:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Linkchecker
          command: apt-get install -y linkchecker
      - run:
          name: Yarn install
          command: yarn install
      - run:
          name: Yarn build
          command: yarn build
      - run:
          name: Install dependencies
          command: pip3 install -r requirements.txt
      - run:
          name: Start development server
          command: ./entrypoint 0.0.0.0:8029
          background: true
      - run:
          name: Wait for development server
          command: sleep 5
      - run:
          name: Run Linkchecker
          command: linkchecker --threads 2 -r 2 --verbose --ignore-url /docs/* --ignore-url /search/* --ignore-url /store/* --ignore-url ".*(?:png|jpg|jpeg|gif|bmp|svg|js)$" --ignore-url /q_auto --ignore-url /case-studies --ignore-url /fl_sanitize --ignore-url /w_* --no-warnings http://0.0.0.0:8029
  check-build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Check the project builds
          command: yarn run build
  python-lint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install flake8
      - run:
          name: Lint webapp with Flake8
          command: yarn run lint-python
  scss-lint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Lint scss with stylelint
          command: yarn run lint-scss
  python-tests:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip3 install -r requirements.txt
      - run:
          name: Install coverage
          command: pip3 install coverage
      - run:
          name: Run tests with coverage
          command: |
            coverage run  --source=. -m unittest discover tests
            bash <(curl -s https://codecov.io/bash) -cF python
workflows:
  version: 2
  build:
    jobs:
      - linkchecker
      - check-build
      - python-lint
      - scss-lint
      - python-tests
