name: PR checks
on: pull_request
env:
  SECRET_KEY: insecure_test_key

jobs:

  run-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: DOCKER_BUILDKIT=1 docker build --tag jaas-ai .

      - name: Run image
        run: |
          docker run --detach --network host --env SECRET_KEY=insecure_secret_key jaas-ai
          sleep 1
          curl --head --fail --retry-delay 1 --retry 30 --retry-connrefused http://localhost

  test-site:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install --yes python3 python3-setuptools
          pip3 install -r requirements.txt
          yarn && yarn run build

      - name:  Check site is accessible
        run: yarn run serve & sleep 3 && curl --head --fail --retry-delay 5 --retry 2  --retry-connrefused http://localhost:8029

  lint-scss:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint scss
        run: yarn lint-scss

  lint-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install node dependencies
        run: yarn install --immutable

      - name: Install python dependencies
        run: sudo pip3 install flake8 black

      - name: Lint python
        run: yarn lint-python

  test-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install requirements
        run: |
          sudo apt-get update && sudo apt-get install --yes python3-setuptools
          sudo pip3 install -r requirements.txt

      - name: Install dependencies
        run: sudo pip3 install coverage

      - name: Run tests with coverage
        run: |
          yarn run test-python
          bash <(curl -s https://codecov.io/bash) -cF python

  check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn

      - name: Check the project builds
        run: yarn run build

  check-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn run check-prettier

  js-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Lint js with eslint
        run: yarn run lint-js
